name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  main_project_module: app
  playstore_name: Frogobox ID

on:
  push:
    branches:
      - 'main'          # Triggers the workflow on the main branch updates
      - 'release/**'    # Keeps the trigger for release branches (optional)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Change permissions for gradlew
      - name: Change wrapper permissions
        run: chmod +x bot-lobby-application/gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test
        working-directory: bot-lobby-application

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
        working-directory: bot-lobby-application

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug
        working-directory: bot-lobby-application

      # Check if the debug outputs directory exists after building
      - name: Check if debug outputs directory exists
        run: |
          if [ -d build/outputs/apk/debug/ ]; then
            echo "Debug outputs directory exists."
          else
            echo "Debug outputs directory does not exist."
          fi
        working-directory: bot-lobby-application

      # List debug outputs to verify files are created
      - name: List debug outputs
        run: |
          echo "Attempting to list debug outputs:"
          ls -la build/outputs/apk/debug/ || echo "Debug outputs directory does not exist."
        working-directory: bot-lobby-application

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleRelease --info
        working-directory: bot-lobby-application

      # Create Bundle AAB Release
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew bundleRelease
        working-directory: bot-lobby-application

      # Check if the release outputs directory exists after building
      - name: Check if release outputs directory exists
        run: |
          if [ -d build/outputs/apk/release/ ]; then
            echo "Release outputs directory exists."
          else
            echo "Release outputs directory does not exist."
          fi
        working-directory: bot-lobby-application

      # List release outputs to verify files are created
      - name: List release outputs
        run: |
          echo "Attempting to list release outputs:"
          ls -la build/outputs/apk/release/ || echo "Release outputs directory does not exist."
        working-directory: bot-lobby-application

      # List AAB outputs to verify files are created
      - name: List AAB outputs
        run: |
          echo "Attempting to list AAB outputs:"
          ls -la build/outputs/bundle/release/ || echo "AAB outputs directory does not exist."
        working-directory: bot-lobby-application

      # Upload Artifact Build
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: bot-lobby-application/build/outputs/apk/debug/

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: bot-lobby-application/build/outputs/apk/release/

      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: bot-lobby-application/build/outputs/bundle/release/
